/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'Users.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'Users.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model/index.js'),
    model   = require('./Users.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("empId").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.users",
    options: {
        tableName: "Users",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "empId": {
            type: Seq.INTEGER,
            field: "empId",
            primaryKey: true,
            allowNull: false,
            unique: "Users_pkey"
        },
        "fullName": {
            type: Seq.STRING(255),
            field: "fullName",
            allowNull: false
        },
        "dOJ": {
            type: Seq.DATEONLY,
            field: "DOJ",
            allowNull: false
        },
        "password": {
            type: Seq.STRING(255),
            field: "password",
            allowNull: false
        },
        "createdAt": {
            type: Seq.DATE,
            field: "createdAt",
            allowNull: false
        },
        "updatedAt": {
            type: Seq.DATE,
            field: "updatedAt",
            allowNull: false
        }
    },
    relations: []
};